# Dependencies
markdown:        redcarpet

#Sass
sass:
    sass_dir:     _sass
    style:        compressed

highlighter:     rouge
gems:
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - deploy.sh

# Setup
title:           MonkeyPatch - Expertise Informatique
keywords:        Expertise informatique, Dévelopement informatique
description:     Société de conseil et d'expertise en informatique spécialisée dans les nouvelles technologies.
url:             http://www.monkeypatch.io
paginate:        1
baseurl:          
author:
    name:        Emmanuel Vinas
    url:         https://twitter.com/EmmanuelVinas
    email:       emmanuel@monkeypatch.io

# Custom vars
version:         1.0.0
github:
    repo:        https://github.com/MonkeyPatchIo/monkeypatchio.github.io

#Contact 
contact:
    tel:         05 34 32 61 45
    tel-link:    0534326145
    mail:        contact@monkeypatch.io
    address:     12 Avenue de l'Europe
    city:        Ramonville-Saint-Agne
    postcode:    31520
    country:     France