
#Sass
sass:
  sass_dir: _sass
  style: compressed

highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-multiple-languages-plugin
#  - jekyll-press
  
exclude:
  - deploy.sh

# Languages
languages:
  - "fr"
#  - "en"
exclude_from_localizations:
  - "public"
  - "_sass"

# Setup
title: MonkeyPatch - Expertise Informatique
keywords: Expertise informatique, Dévelopement informatique
description: Société de conseil et d'expertise en informatique spécialisée dans les nouvelles technologies.
url: http://www.monkeypatch.io

twitter:
  username: MonkeyPatch_io

logo: /public/images/logos/logo-mkp-blue.png
social: 
  links:
    - "https://twitter.com/monkeypatch_io"
    - "https://www.linkedin.com/company/monkeypatch-io" 

# Custom vars
version:         1.0.0
github:
  repo:        https://github.com/MonkeyPatchIo/monkeypatchio.github.io

# Contact 
contact:
  tel:         05 34 32 61 45
  tel-link:    0534326145
  mail:        contact@monkeypatch.io
  address:     12 Avenue de l'Europe
  city:        Ramonville-Saint-Agne
  postcode:    31520
  country:     France

# Collections
collections:
  expertise:
    output: false
  teams:
    output: false
  jobs:
    output: false
  profiles:
    output: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
      order: 0
  - # Expertises
    scope:
      path: "_expertise/fr"
    values:
      lang: fr
  -
    scope:
      path: "_expertise/fr/offers"
    values:
      type: offers
  -
    scope:
      path: "_expertise/fr/interventions"
    values:
      type: interventions
  -
    scope:
      path: "_expertise/fr/profiles"
    values:
      type: profiles
  - # Teams
    scope:
      path: "_teams/fr"
    values:
      lang: fr
  - # profiles
    scope:
      path: "_profiles/fr"
    values:
      lang: fr
  -
    scope:
      path: "_profiles/fr/assets"
    values:
      type: assets
  -
    scope:
      path: "_profiles/fr/profiles"
    values:
      type: profiles
