
#Sass
sass:
  sass_dir: _sass
  style: compressed


gems:
  - jekyll-paginate
  - jekyll-multiple-languages-plugin
  - octopress-autoprefixer
  - jekyll-press

# Blog pagination
paginate: 5
paginate_path: "/blog/p:num/"
future: true

excerpt_separator: "<!--more-->"
highlighter: rouge
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

exclude:
  - deploy.sh

# Languages
languages:
  - "fr"
  - "en"
exclude_from_localizations:
  - "public"
  - "css"
  - "_sass"

# Setup
title: MonkeyPatch - Expertise Informatique
keywords: Expertise informatique, Dévelopement informatique
description: Société de conseil et d'expertise en informatique spécialisée dans les nouvelles technologies.
url: http://www.monkeypatch.io

twitter:
  username: MonkeyPatch_io
  link: https://twitter.com/monkeypatch_io

google:
  map:
    iframe: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2891.6225725756276!2d1.4868599515209782!3d43.55190887902245!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12aebdd6314e8b39%3A0x61a8203a28bb90fc!2sMonkeyPatch!5e0!3m2!1sfr!2sfr!4v1468852963039"

logo: http://www.monkeypatch.io/public/images/logos/logo-mkp-head-blue-x126.png


social: 
  logo: http://www.monkeypatch.io/public/images/logos/logo-mkp-blue-x256.png
  links:
    - "https://twitter.com/monkeypatch_io"
    - "https://www.linkedin.com/company/monkeypatch-io" 

# Custom vars
version: 1.0.0
github:
  repo: https://github.com/MonkeyPatchIo/monkeypatchio.github.io

mail:
  server: http://192.168.1.160:9090

# Contact 
contact:
  name: MonkeyPatch
  tel: 05 34 32 61 45
  tel-link: 0534326145
  mail: contact@monkeypatch.io
  address: 12 Avenue de l'Europe
  city: Ramonville-Saint-Agne
  postcode: 31520
  country: France

# Collections
collections:
  posts:
    output: true
  expertise:
    output: false
  teams:
    output: false
  jobs:
    output: true
  profiles:
    output: false

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
      order: 0
  - # Expertises
    scope:
      path: "_expertise/fr"
    values:
      lang: fr
  - scope:
      path: "_expertise/fr/offers"
    values:
      type: offers
  - scope:
      path: "_expertise/fr/interventions"
    values:
      type: interventions
  - scope:
      path: "_expertise/fr/profiles"
    values:
      type: profiles
  - # Teams
    scope:
      path: "_teams/fr"
    values:
      lang: fr
  - # Jobs
    scope:
      path: "_jobs"
    values:
      layout: job
  - 
    scope:
      path: "_jobs/fr"
    values:
      lang: fr
  - # profiles
    scope:
      path: "_profiles/fr"
    values:
      lang: fr
  - scope:
      path: "_profiles/fr/assets"
    values:
      type: assets
  - scope:
      path: "_profiles/fr/profiles"
    values:
      type: profiles
  - # Blog
    scope:
      path: "_posts"
    values:
      layout: post
      comments: true
      published: true
  - scope:
      path: "_posts/fr"
    values:
      lang: fr
      comments: true
  - # Blog Draft
    scope:
      path: "_drafts"
    values:
      layout: post
      comments: true
  - scope:
      path: "_drafts/fr"
    values:
      lang: fr
